bundler_args: --without documentation
script: bundle exec rake compile test
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install openssl; fi'
env:
  global:
    - TESTOPTS=-v
language: ruby
sudo: false
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ruby-head
  - rbx
  - rbx-2
#  - jruby-1.7
#  - jruby-9
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: 2.0.0
    - rvm: 2.0.0
      os: osx
      osx_image: xcode7.2
#    - rvm: jruby-1.7
#    - rvm: jruby-9
  include:
    - rvm: 2.0.0
      os: osx
      osx_image: xcode7.2
