dist: xenial
language: ruby
bundler_args: --without documentation

before_install:
  # rubygems 2.7.8 and greater include bundler
  # remove 2.7.0 code when Travis removes rubygems 2.7.8 from ruby-head build
  - |
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if   [ "$rv" \< "2.3" ]; then gem update --system 2.7.8 --no-document
    elif [ "$rv" \< "2.7" ]; then gem update --system --no-document --conservative
    fi

before_script:
  - bundle exec rake compile

script:
  - bundle exec rake test

env:
  global:
    - TESTOPTS="-v  --no-show-detail-immediately"
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - ruby-head
#  - rbx
#  - rbx-2
#  - rbx-3
#  - jruby-1.7
#  - jruby-9
matrix:
  fast_finish: true
  allow_failures:
#    - rvm: rbx
#    - rvm: rbx-2
#    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: 2.3
      os: osx
#    - rvm: jruby-1.7
#    - rvm: jruby-9
  include:
    - rvm: 2.3
      os: osx
