sudo: false
dist: trusty
language: ruby
bundler_args: --without documentation
script: bundle exec rake compile test
# Pin Rubygems to a working version. Sometimes it breaks upstream. Update now and then.
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install openssl; fi'
  - gem update --system 2.7.4
  - gem update bundler
env:
  global:
    - TESTOPTS=-v
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - ruby-head
#  - rbx
#  - rbx-2
#  - rbx-3
#  - jruby-1.7
#  - jruby-9
matrix:
  fast_finish: true
  allow_failures:
#    - rvm: rbx
#    - rvm: rbx-2
#    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: 2.0.0
    - rvm: 2.3
      os: osx
#    - rvm: jruby-1.7
#    - rvm: jruby-9
  include:
    - rvm: 1.8.7
      dist: precise
    - rvm: 2.3
      os: osx
